name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: npm test

      - name: Determine Docker tag
        id: tagger
        shell: bash
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            # For PRs, use the feature branch name
            echo "tag=pr_${{ github.event.number }}" >> $GITHUB_OUTPUT
          else
            # For other branches (like development), use the branch name
            echo "tag=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and publish a Docker image
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: ${{ steps.tagger.outputs.tag }}
