name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: "ubuntu-24.04"

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: docker/build-push-action@v2
        with:
            platforms: linux/amd64,linux/arm64,linux/arm/v7
            push: true
            tags: ghcr.io/lordvault/actual-budget-rest-api:${{ github.head_ref }}