name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches-ignore: [ "main" ]

jobs:

  build:

    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v2

      - name: Get actual-app/api version from package.json
        id: get-version
        run: |
          export ACTUAL_API_VERSION=$(jq -r '.dependencies["@actual-app/api"] | ltrimstr("^")' package.json)
          echo "ACTUAL_API_VERSION=$ACTUAL_API_VERSION" >> $GITHUB_ENV
          echo "ACTUAL_API_VERSION=$ACTUAL_API_VERSION" >> $GITHUB_OUTPUT

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: paulcoates/actual-budget-rest-api
          github_token: ${{ secrets.GHCR_PUBLISH }}
          image_tag: development