name: Build and publish a Docker image to ghcr.io
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: "ubuntu-24.04"

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: loomchild
            password: ${{ secrets.GITHUB_TOKEN }}  
      
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: docker/build-push-action@v6
        with:
            platforms: linux/amd64,linux/arm64
            push: true
            tags: ghcr.io/lordvault/actual-budget-rest-api:${{ github.head_ref }}